
export const INITIAL_STATE = {
  balance: 1000000,
  assets: [],
  transactions: [],
  name: "Fintech Student",
  accountId: "CW-AI-8892-X",
  competition: {
    isCompeting: false,
    entryNetWorth: 0,
    entryTime: 0,
    endTime: 0,
    roundId: "",
    pnlPercent: 0,
    currentRank: 0
  }
};

export const CRYPTO_SYMBOLS = [
  // Majors & High Caps
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'ADAUSDT', 'DOGEUSDT', 'AVAXUSDT', 'DOTUSDT', 'TRXUSDT',
  'LINKUSDT', 'MATICUSDT', 'WBTCUSDT', 'UNIUSDT', 'LTCUSDT', 'SHIBUSDT', 'DAIUSDT', 'BCHUSDT', 'ATOMUSDT', 'ICPUSDT',
  
  // L1s & Infrastructure
  'NEARUSDT', 'XLMUSDT', 'ETCUSDT', 'XMRUSDT', 'OPUSDT', 'INJUSDT', 'TIAUSDT', 'LDOUSDT', 'FILUSDT', 'STXUSDT',
  'RUNEUSDT', 'APTUSDT', 'SUIUSDT', 'ARBUSDT', 'MKRUSDT', 'AAVEUSDT', 'GRTUSDT', 'RNDRUSDT', 'EGLDUSDT', 'FLOWUSDT',
  'THETAUSDT', 'ALGOUSDT', 'QNTUSDT', 'SANDUSDT', 'MANAUSDT', 'EOSUSDT', 'KAVAUSDT', 'AXSUSDT', 'NEOUSDT', 'CHZUSDT',
  'FTMUSDT', 'IOTAUSDT', 'CFXUSDT', 'KLAYUSDT', 'GALAUSDT', 'ZECUSDT', 'SNXUSDT', 'MINAUSDT', 'CRVUSDT', 'CAKEUSDT',
  
  // DeFi & L2
  'DYDXUSDT', '1INCHUSDT', 'LRCUSDT', 'ENSUSDT', 'JASMYUSDT', 'PEPEUSDT', 'BONKUSDT', 'FLOKIUSDT', 'ORDIUSDT', '1000SATSUSDT',
  'PYTHUSDT', 'JUPUSDT', 'MANTAUSDT', 'ALTUSDT', 'BEAMXUSDT', 'SEIUSDT', 'WOOUSDT', 'PENDLEUSDT', 'AGIXUSDT', 'FETUSDT',
  'OCEANUSDT', 'ANKRUSDT', 'ROSEUSDT', 'GLMRUSDT', 'ASTRUSDT', 'BTTUSDT', 'IOTXUSDT', 'CKBUSDT', 'WAVESUSDT', 'ZILUSDT',
  'RVNUSDT', 'HBARUSDT', 'STGUSDT', 'GMXUSDT', 'IDUSDT', 'MAGICUSDT', 'LUNCUSDT', 'USTCUSDT', 'BLURUSDT',
  
  // New Trending & Ecosystem Additions
  'WIFUSDT', 'BOMEUSDT', 'NOTUSDT', 'STRKUSDT', 'ENAUSDT', 'ONDOUSDT', 'ETHFIUSDT', 'WUSDT', 'ZROUSDT', 'ZKUSDT',
  'LISTAUSDT', 'IOUSDT', 'BBUSDT', 'TAOUSDT', 'PORTALUSDT', 'AXLUSDT', 'METISUSDT', 'DYMUSDT', 'RONINUSDT', 'PYTHUSDT',
  'ACEUSDT', 'JITOUSDT', 'AEVOUSDT', 'PIXELUSDT', 'SAGAUSDT', 'TNSRUSDT', 'OMNIUSDT', 'REZUSDT', 'NOTUSDT', 'ZKUSDT',
  'WUSDT', 'EIGENUSDT', 'TURBOUSDT', 'NEIROUSDT', 'CATIUSDT', 'HMSTRUSDT', 'SCRUSDT', 'PUPPIESUSDT', 'AAVEUSDT',
  
  // Additional Institutional/Utility
  'COMPUSDT', 'SUSHIUSDT', 'YFIUSDT', 'BALUSDT', 'KNCUSDT', 'ZRXUSDT', 'BATUSDT', 'ANKRUSDT', 'RENUSDT', 'KSMUSDT',
  'ICXUSDT', 'ONTUSDT', 'ZILUSDT', 'WAVESUSDT', 'QTUMUSDT', 'LSKUSDT', 'SCUSDT', 'DENTUSDT', 'HOTUSDT', 'NKNUSDT',
  'DATAUSDT', 'STMXUSDT', 'PERPUSDT', 'REEFUSDT', 'TRUUSDT', 'BADGERUSDT', 'ALICEUSDT', 'SUPERUSDT', 'DEGOUSDT',
  'PONDUSDT', 'LINAUSDT', 'PERPUSDT', 'TKOUSDT', 'PUNDIXUSDT', 'MIRUSDT', 'POLSUSDT', 'MDXUSDT', 'MASKUSDT', 'LPTUSDT'
];

export const BINANCE_REST_API = "https://api.binance.com/api/v3";
export const ENTRY_FEE = 5.00;
export const MAX_PRIZE_POOL = 50000;
export const BASELINE_NET_WORTH = 1000000;
